# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcp-gimp" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "5601a250bead199c4726759a2c6607eae977c8f1e551dc4b49bde9af5e8c9490"
      url "https://github.com/ryancurrah/mcp-gimp/releases/download/v#{version}/mcp-gimp_Darwin_arm64.tar.xz"
      rename "mcp-gimp_Darwin_arm64/mcp-gimp", "mcp-gimp"
    end
    on_intel do
      sha256 "563d17b89cda10c8ba3a49fbe7ad9e8627ebf8d43fa1b51ee7ed47a3d51f439a"
      url "https://github.com/ryancurrah/mcp-gimp/releases/download/v#{version}/mcp-gimp_Darwin_x86_64.tar.xz"
      rename "mcp-gimp_Darwin_x86_64/mcp-gimp", "mcp-gimp"
    end
  end
  on_linux do
    on_arm do
      sha256 "a15ad79771713c2dacdbe7f163996a6e025d57ec48d71bf17d25e5f882edecda"
      url "https://github.com/ryancurrah/mcp-gimp/releases/download/v#{version}/mcp-gimp_Linux_arm64.tar.xz"
      rename "mcp-gimp_Linux_arm64/mcp-gimp", "mcp-gimp"
    end
    on_intel do
      sha256 "727ffe06b054c9216668cf7846ed6bf8a296b4a3efbc74e1ac88985135d174ab"
      url "https://github.com/ryancurrah/mcp-gimp/releases/download/v#{version}/mcp-gimp_Linux_x86_64.tar.xz"
      rename "mcp-gimp_Linux_x86_64/mcp-gimp", "mcp-gimp"
    end
  end

  name "mcp-gimp"
  desc "MCP server for GIMP 3"
  homepage "https://github.com/ryancurrah/mcp-gimp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcp-gimp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcp-gimp"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The other half of mcp-gimp runs inside GIMP:
      brew install --cask ryancurrah/tap/gimp-mcp-plugin
  EOS
end
